### ISSUE TITLE
Text gets cut off on main screen

### ISSUE THREAD

**Issue by FutureProg** [Flaque/quirk#117]
The app text gets cut off on the main screen on OnePlus 6T. Quirk in the title becomes Quir; Labeling becomes La-; Save becomes Sav. There is room for the text though, so I'm not certain why it's happening. Is anyone working on fixing this?  

Screenshot: https://drive.google.com/open?id=1-WkGEaivaEfHcfR7PoQ-UW0SDjkt4V7o

**Comment by Flaque** [comment]
Woah, this is real weird. Definitely a bug.

**Comment by doro** [comment]
![quirk_intro_cut](https://user-images.githubusercontent.com/418015/58956035-0df52000-87a6-11e9-915b-6e57e2c25c81.PNG)
Text also gets cut on the Intro, on the cbt_overview section.

**Comment by devinroche** [comment]
@Flaque not sure if you fixed this issue but from what @doro said we could probably change this line https://github.com/Flaque/quirk/blob/a0904979259d030a6b749491359264f047d3876d/src/CBTOnBoarding.tsx#L43 to `667` since thats the [height of iphone 6](https://www.paintcodeapp.com/news/iphone-6-screens-demystified)
