### ISSUE TITLE
What about custom distortions?

### ISSUE THREAD

**Issue by idmitrievsky** [Flaque/quirk#121]
First of all, great app, really enjoying it!

I wanted to remove some of the distortions that don't appear in my thoughts just to streamline the process of logging an automatic thought a bit more, but there is no way to do it currently.

Maybe the app could come with a set of distortions, but users could remove and add (I wanted to add "filtering" to my distortions) any of them?

Does this seem useful? If so, there is a question of what to do, when you remove a distortion, but there are thoughts in your history associated with this distortion. Maybe archiving instead of removing is a way around that issue.

**Comment by Flaque** [comment]
Ah, so there's two things here:
- Adding new distortions
- Removing existing ones 

For adding new distortions, I would be down to see this happen. For removing existing distortions, this is something I investigated and eventually decided not to do due to the recommendations of some clinicians. 

The reason is that so, so many folks misunderstand how often their thoughts are distorted. Myself included! I've got panic attacks and so for the longest time, I entirely ignored most distortions.

In fact, I removed distortions I "didn't need" from a pre-released version of Quirk (back when it was a hacky script). It was until I added a bunch more back for the release version that I _really_ started recognizing "Emotional Reasoning" and gained this whole big insight about how I could use my own panic to justify more panic.

So leaving things you think you "don't need" is the easiest way to get folks to explore a bit.

**Comment by iamLoi** [comment]
One of the primary strength of this app is the simplicity. I think the default distortions already encompass most cognitive distortions that people encounter. It's fairly comprehensive. Adding custom distortions would certainly lengthen the list and add more complexity to a simple exercise. CBT only works if people stick to it consistently and adding more complexity would be counterproductive.

**Comment by Flaque** [comment]
Closing this since at the moment we're probably going to avoid this for the moment

**Comment by idmitrievsky** [comment]
Yeah, you raise valid points, it doesn't seem like the app would benefit from this feature. Thank you for your feedback!

**Comment by Flaque** [comment]
@idmitrievsky no, thank you! Seriously, thanks for being a part of this! ❤️
