### ISSUE TITLE
Still taking 30+ seconds to load on iOS 12

### ISSUE THREAD

**Issue by iamLoi** [Flaque/quirk#138]
This is similar to issue #98 but on iOS and much longer than 15 seconds. Happens nearly every single time and is a significant issue. Airplane mode is a workaround, but needs a better solution ASAP.

**Comment by Flaque** [comment]
So the reason this happens is because Expo lets us push out over the air updates. When that happens, it'll show a longer-than-normal loader and load the update in the background. It's happening nearly every single time... because we update basically every day now. 

If you try to Airplane-mode it in the middle of an update a lot, it'll show you: #139, which happens (I think) because you don't have a recent update for it to fall back to. 

There's some configuring we can do here though to help solve this: https://docs.expo.io/versions/latest/guides/configuring-ota-updates/

I would _prefer_ that we don't set the fallback timer to 0, since often we ship out updates to fix some urgent problem. But we could set it to 10 or 15, which would effectively set a "max" time for the update.

**Comment by iamLoi** [comment]
This app is fairly simple and static. Everything is supposed to reside on my phone and it doesn’t even have to fetch anything from the server, so why does it need to ship updates that often? What type of updates are we talking about that can’t be shipped through the App Store like every other apps? 

If OTA is the problem, then it needs to be disabled because waiting 30-60 (or even 10-15) seconds for an app to load is a dealbreaker for me.

**Comment by Flaque** [comment]
> so why does it need to ship updates that often

Features! Bugs! Me messing up 😭 It's nothing to do with what's being fetched from the server. It's just daily updates. 

The App Store takes like a week for every update so stuff would be broken or bad quite quickly. We use Expo so we can immediately fix and change stuff.

> Disabled 
There's a thing we can do to make it load in the background instead. I'll add something for that.
