### ISSUE TITLE
Not found on Play Store

### ISSUE THREAD

**Issue by agucova** [Flaque/quirk#170]
I'm not sure if this is a regional issue (I'm on Chile), but when I click the Play Store [link](https://play.google.com/store/apps/details?id=tech.econn.quirk) for the app, I always get:

> We're sorry, the requested URL was not found on this server.

The same happens when searching the app directly through the store. Was the app removed from the Play Store, or is it simply not available in Chile?

**Comment by pricecomstock** [comment]
Same here in the US

**Comment by agucova** [comment]
And seeing how I had the app installed but it dissappeared from the Store, I'm going for the first hypothesis, it was taken down.

At this point I wouldn't be surprised if a heuristic thought it was malware or something 🙄

**Comment by Jos512** [comment]
It's not available in the Dutch Play store either.

I'm afraid the reason why is that the project seems discontinued. The last code commit was 6 months ago (October 6). Since the developer (Evan) was working full-time on Quirk, it seems he has sadly moved on. 

I hope he is fine and nothing serious happened. Luckily he's still very active on GitHub with another project. So that would suggest he's still reasonably fine and still working, but just not on Quirk anymore.

**Comment by Flaque** [comment]
Hey folks, @Jos512 is correct. Apologies, the company behind Quirk (the way we were able to work on this full time) ran into ethical issues that made us shift away.

In order for the company to survive, we needed folks to subscribe long enough. But as folks did better, they unsubscribed. Since we didn't want people to _not_ feel better, we decided that we were going to pivot the _company_ of Quirk towards a different project and let the _app_ Quirk open for someone else to take. Part of that meant that we no longer have the resources to maintain Quirk. It was a hard decision, but I never wanted to make people feel worse. 

At the moment, there's a couple different forks of Quirk going on, though I'm not quite clear of the statuses.

Our new project is still "Quirk" the company, but with a different product. We left mental health world entirely and are making a dev tool: https://www.roomservice.dev/ We were not the folks to do mental health tech, but maybe we could help the right folks do it. 

This project will also be reasonably driven by open-source, though much like Quirk, most of it is closed until we're ready to launch.

**Comment by qazip** [comment]
That sucks! I just came back to try to use this app after a while and I come across this issue.. Hopefully someone picks this up. This app is incredibly important in the mental health scene, possibly life-changing. 

@Flaque, can you provide links to the "couple different forks of Quirk going on"? I couldn't find it easily..

**Comment by Flaque** [comment]
@qazip they're not "launched" yet afaik :/ 

That said, if others want to take this and run with it, I would fork off of this commit: 7a4eabe48414de5edfefcd693e79178120eae142 

That commit is right before we ejected from Expo and it was the most easy to spin up and develop. It's also my favorite version of the app.

**Comment by Jos512** [comment]
Sorry to hear @Flaque that it didn't work out! But I'm glad to hear no accident or other problem happened to you and your team.

Thanks for all the work you put into Quirk. :hugs: Good luck on the new Roomservice service!

**Comment by erosson** [comment]
For anyone who stumbles across this issue in the future: [my Quirk fork, FreeCBT](https://github.com/erosson/freecbt), is now [live on the Play Store](https://play.google.com/store/apps/details?id=org.erosson.freecbt)!
