### ISSUE TITLE
Make an android version

### ISSUE THREAD

**Issue by evexoio** [Flaque/quirk#27]
I see the codebase is in react-native,

Can you share the reasoning behind not having an apk already?

**Comment by Flaque** [comment]
The Android version is definitely coming. 

> Can you share the reasoning behind not having an apk already?

Mainly I just wanted to get feedback on it ASAP and setting it up one with one platform is easiest. Plus, I have an iPhone so it's a lot easier for me to prototype and develop for it on iOS first. But I built this in react native so that I could easily develop cross platform.

**Comment by evexoio** [comment]
@Flaque I can help with fixing any bugs in the android version, actually I just started testing it now 👍

**Comment by Flaque** [comment]
If you test it on a physical device, let me know if there's anything _obviously_ wrong with it! ❤️

**Comment by Flaque** [comment]
Technically done: https://play.google.com/store/apps/details?id=tech.econn.quirk Though might be a bit buggy
