### ISSUE TITLE
Improvement: Thoughts can be deleted without user confirmation, add confirmation?

### ISSUE THREAD

**Issue by sandersantema** [Flaque/quirk#31]
Maybe it would be better if deleting thoughts would require confirmation or the usual swipe to delete button?

**Comment by Flaque** [comment]
A confirmation step or a double tap might work, but haven't figured out how to do it quite yet.

**Comment by Jos512** [comment]
Perhaps an alternative would be to show a small message in the bottom of the screen, like this?

> Removed entry. **Undo**.

Some kind of recovery from an accidental remove is important, I think. I at least already accidentally removed a thought, and it doesn't feel good. :slightly_smiling_face: 

---

Perhaps we can even extend this 'undo deletion' feature to recent *n* days? Since this app deals with cognitive distortions, I might think:

> That was a useless thought to record.

or:

> I'm ashamed for that thought and recording it.

But then only to later come back from that idea, and want to keep the thought.

**Comment by Flaque** [comment]
> small message in the bottom of the screen

This seems like a good first step, should be feasible with the alert components.  

> Perhaps we can even extend this 'undo deletion' feature to recent n days?

I like that a lot. Thoughts on an archive?

**Comment by pgoodman** [comment]
I think it would be nice to have a kind of recycling bin or something so that deleted entries can be retrieved (perhaps at least for a time).

**Comment by Jos512** [comment]
Let's not close this issue. A deletion confirmation is pretty important, I think. Nearly all other software apps in the last 20 years seem to agree, Mr. Stale bot. :laughing:

**Comment by Flaque** [comment]
That... is a good point 👍 Deletion confirmation is definitely on the list of things to do. 👍

**Comment by shubhamkakkar** [comment]
What about a simple alert confirmation message
Alert.alert() of react native ?
Or are we looking forward for something with better UI?

**Comment by Flaque** [comment]
This is coming in the new redesigned Quirk: 

![screenshotcast](https://user-images.githubusercontent.com/5942769/61582478-bf4add80-aae8-11e9-8c1e-58c481ceb80e.gif)
