### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by NihalNazim33582** [Flaque/quirk#359]
An issue I found in the app is with the navigation. The navigation thought the screens are made hard because the objects that are supposed to represent what direction you are going in are where the navigation tool was are missing.

**Comment by wimpyKid781** [comment]
Some of these links might help you understand what is going wrong.
https://reactnative.dev/docs/navigation
https://reactnavigation.org/
https://github.com/wix/react-native-navigation
https://www.npmjs.com/package/react-native-navigation
I have also created some programs using react-navigation. I have added the links here.
https://snack.expo.io/@awesomeaaron7/newsletter-project
https://snack.expo.io/@awesomeaaron7/wireless-buzzer-database
https://snack.expo.io/@awesomeaaron7/switch-navigator
I could not be more specific, because your question was not very specific, but I really hope this helps!!
