### ISSUE TITLE
Consider mentioning that thoughts are only saved locally

### ISSUE THREAD

**Issue by michaelrhodes** [Flaque/quirk#51]
Given that thoughts are quite sensitive, I think it might be worth telling folks during on-boarding that their data will never leave the device. Down the line it might even be a good idea to allow passcode protection of the list screen, but that’s just thinking out loud.

**Comment by Flaque** [comment]
>  think it might be worth telling folks during on-boarding

I'd prefer to have this info somewhere else. 

Quirk is not a privacy product, it's a CBT app that happens to be fairly private. Most people come to the product for mental health concerns and that's top of their mind.

It's the job of engineers like us to just make stuff happen for them behind the scenes. We're trusted to just do stuff the right way. You don't see a big sign on the Golden Gate bridge about the structural quality of the bolts, you just assume that it will hold up as you're driving by. 

Quirk is the same, it's private because privacy should be a given in a mental health app. It's open source so folks like yourself can verify that nothing shady is going on. But neither the privacy nor the open source is particularly important to folks outside the tech bubble.

On the other hand, I would be happy to include this info in the app _somewhere_. I do think that Quirk has a responsibility to set the standard for mental health apps. If these things _should_ be private than more people should _expect_ it, which Quirk can help with. Just not sure yet.

> to allow passcode protection of the list screen

This is the next thing on the roadmap after internationalization, but is a "big" project so it'll require a lot of thought.

**Comment by idnovic** [comment]
about the saving part, what about a backup or sync feature?
On iOS you would use iCloud.

#encrypted storage
https://docs.expo.io/versions/latest/sdk/securestore/

#iCloud sync
https://github.com/manicakes/react-native-icloudstore

**Comment by kuperov** [comment]
This. I just spent half an hour trying to work this out. I wasted time scouring the website, etc, only to end up having to reading the source code. One sentence somewhere would be great.

**Comment by Flaque** [comment]
@kuperov Hmmmm, I'll put it on the website then.
