### ISSUE TITLE
Export / Backup / sync saved entries

### ISSUE THREAD

**Issue by adig** [Flaque/quirk#80]
I was wondering if you have any plans for allowing users to export the saved data in any way. 

I see that the entries are only saved locally, so the options are: 

- have an on-demand "Export option" (format TBD)
- have a sync / backup option where the data is stored in iCloud automatically, allowing the user to get the data from there if required (iCloud data should be human readable)

Any thoughts? I'd be happy to implement this and submit a PR if you can give me some directions. 

Thanks!

**Comment by idnovic** [comment]
#86

**Comment by idnovic** [comment]
about the saving part, what about a backup or sync feature?
On iOS you would use iCloud.

#encrypted storage
https://docs.expo.io/versions/latest/sdk/securestore/

#iCloud sync
https://github.com/manicakes/react-native-icloudstore

#fingerprint
https://docs.expo.io/versions/latest/sdk/local-authentication/

_Originally posted by @idnovic in https://github.com/Flaque/quirk/issues/51#issuecomment-480618560_

**Comment by notbenh** [comment]
Sync would be nice but really export to pdf and csv are really all that would be required at this point as you can do the share via other means.

**Comment by Flaque** [comment]
Curious what the use case for sync is. Is it more:
- I want to use this on multiple devices?
- I never want to lose these thoughts

**Comment by adig** [comment]
The use case I had in mind was about not losing data. I guess using the same data across devices would be a bonus feature. 

As far as I understand, if you're backing up your phone, it will include the app data, so in case of failure you can restore the app and the data.

The use case that's not covered is exporting the data in case you want to use a different app/method/don't like the app anymore/whatever. The easiest would be an option to export as CSV. I can look into PDF creation libraries if it seems useful.

**Comment by murarisumit** [comment]
Adding few of my thoughts here.

I prefer data across devices, icloud afaik is apple device only, if we can have something on lines of dropbox/gdrive/onedrive which are on various platform, i can play with this app on both my devices. 

Android is my primary device and also have an apple device, so for me dropbox/gdrive/onedrive(cross-platform) are better suited.  Encryption would be super-super+1. I know adding feature can be time-consuming, and understandable if not implemented too.

CSV's would be nice and can be re-imported too, imo that is good option. Adding more to it, if we can auto-export after a week/10days/something would be beautiful, then I wouldn't have to take care of backing up.

**Comment by jatoo** [comment]
A good use case for this could be to print it out and take it to your psychologist or counsellor.

**Comment by Flaque** [comment]
This is a whole bunch of things features all in one thing, but end-to-end encrypted syncing is something we're working on.

# How it could work
(please critique this, not 100% sure if this is right)

- You'd have an account. 
- We encrypt your thoughts **on the device** using your password as the key.
- We upload the encrypted thoughts to a DB somewhere protected by your user/pass combo.
- If you get a new phone or device, you log on, we pull the thoughts down and decrypt them on the device.

## Benefits
We (Quirk) never store your raw thoughts. We have no ability to. Therefore, a data breach can't leak a bunch of people's thoughts.

## Downsides
- Resetting passwords is _kinda_ impossible. You could reset your password, but you would lose all your old thoughts. 
- Most people's passwords are bad.

**Comment by idnovic** [comment]
I think your suggestion works as a base. Later you can improve it by using the hardware key storage of modern devices and fingerprint instead of passwords.

Apple devices are special in that sense. Because you can let the device handle the key chain and sync. As long as the user has access to his/hers apple id, quirk would never loose the encryption key.

On the storage side of things, do you really want to store on own infrastructure? I mean iCloud, Dropbox and GDrive are kinda next level things. From my perspective let them handle the storage.

**Comment by Flaque** [comment]
@idnovic 
re: hardware keystorage --> What would happen if these become outdated in the next phone cycle? (Which is presumably a pretty common reason someone might get a new phone)

re: storage --> Very much so. If we used iCloud, a user couldn't switch to Android without losing their thoughts. With Dropbox and GDrive, a user would have to make a dropbox and gdrive in order to use Quirk. 

Plus, doing it that way would be a nightmare in permissions issues that I don't really want to deal with. I'd much rather spin up a really simple DB with backups. It's boring and therefore there's no weird problems with it.

**Comment by idnovic** [comment]
On Apple devices the key chain is synced across all devices. Phone, tablet, mac, ...
So for the encryption you can use a key inside the key chain (software).
But instead of asking the user for a password every time, you add a hardware bound key (hardware keystorage) to unlock/open the key in the software key chain. Or just ask for the fingerprint. On Apple devices you do not need to handle the key transfer yourself.

What you are describing works like this:
UserPassword (derivatives Key) de/encrypts  AesEncryption for DB

What I am describing works like this:
Fingerprint authenticates HardwareBoundKey unlock KeyChain (Software) de/encrypts AesEncryption for DB

Your version is simpler and easier cross platform. 
With my version the UserPassword is never used for the encryption but only to unlock a key. The key itself is used for the encryption.
Because the KeyChain (software) key does the encryption it is possible to let the device (apple) sync across all devices. User does not lose the key.
The user is not asked to authenticate with a password, instead we used the fingerprint to unlock the KeyChain. The hardware bound key is optional. You can add it in between the fingerprint and the software KeyChain to increase security.

For quirk, it is preferable to follow your idea. Just do not make the crypto yourself.
I recommend to look into pbkdf2
https://crypto.stackexchange.com/questions/46955/what-is-the-correct-way-to-implement-pbkdf2-aes-cbc-hmac
https://stackoverflow.com/questions/21074315/encryption-of-string-aes-pbkdf2

**Comment by murarisumit** [comment]
Adding DB somewhere would incur some cost, for dropbox/drive third party sign-up is required, we can have both. We can have integration to dropbox/gdrive/iclould and also if people want to host on DB with us(which gives them easier simpler and easier cross platform without third-party service), we can ask for sort-of premium. 
This would allow some people to use app for free and also have optional premium feature and help qurik reach wider audience and have larger impact.

**Comment by idnovic** [comment]
I am thinking about server maintenance and hardware failure. You would need to make sure you are good to go. Also because of gdpr you may want to think about it again.

**Comment by Flaque** [comment]
**Re: DB cost, server maintenance, and hardware failure** 
I'm not super worried about this. Cost is pretty cheap, like maximum we would spend is a few hundred a month, but a more reasonable amount is like $0-20 a month. For Quirk-the-business, that's fine. 

As for maintenance and hardware failure, managed DBs are pretty darn good these days. Automatic backups, sharding, automatic recovery from failure, the whole shebang. Just using Heroku or something can make it an almost entirely set-it-and-forget-it deal for pretty cheap.

Plus, we don't actually have that much data. Let's say in the far future Quirk has 50k folks and they're all recording 365 thoughts a year. Assuming a max thought size of about 3kb, we'd be looking at around ~65gib, which just isn't that big as a maximum.

**Re: dropbox/drive**
I think for the vast majority of non-developer people, this would freak them out. _Very_ few apps do something like this. 

Equally spooky is that we give users access to their _encrypted_ files. Which for a regular user might look like we're dumping "viruses" or other "dangerous" content into their dropbox. It also is _encrypted_ files that _they can edit_, which means they can easily corrupt their own files. 

**Re: free-vs-premium**
I'd like to avoid splitting folks up into two camps at the moment. We want to be extremely cautious and thoughtful about what we're doing when we're pricing stuff; it creates all these external effects that can be hard to anticipate.

For example, pricing is a signal of value to a user. So if you split out part of your features as "paid" and others as "free", you teach the user which parts of your app are valuable and which parts they should care about. 

For us, the _most_ valuable part of Quirk is the recording, not the viewing or storing thoughts. At least that's the most important from a CBT perspective.

Similarly, splitting up your user base can create negative incentives for Quirk-the-buisness. If Quirk does well, there's a good chance we'll hire folks and the business will grow. To ensure that Quirk of the future is the ethical, good-for-the-world company that we want it to be, we care a _lot_ about what incentives our business model is creating.

When you split people up, you create an incentive to either monetize your free users (ads, data collection generally) or hound them consistently to join your paid version. Because if you don't, your company will die, everyone loses their jobs, and Quirk dies.

**Comment by murarisumit** [comment]
> To ensure that Quirk of the future is the ethical, good-for-the-world company that we want it to be, we care a lot about what incentives our business model is creating.
I can understand your point of view, which makes sense too. For non-developer people it makes sense to have seamless experience, like all other apps give and convenience is priority. I was coming from my perspective, which are not the audience can sustain Quirk-the-buisness entirely.
All the best :+1:

**Comment by Flaque** [comment]
Oh course, thank you for the suggestions/feedback none the less, it's still something important to think about. 

also @idnovic --> I don't think we'll have to worry about toooo much GDPR concerns as long as the data is encrypted and easily delete-able. That said, your responsibilities are often the same, regardless of how you store the data.

**Comment by ahcyip** [comment]
so, is there some way to export/save? would like to keep my data somehow
